name: Release
on:
  pull_request:
    branches: master
    types: closed
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && true == contains(join(github.event.pull_request.labels.*.name), 'Release')
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/release@master
### Going to try my version of their release automation
#### This does not work, going to go back to trying elementary's
#    - uses: timecraft/actions/release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_branch: 'hera'
